[build-system]
requires = ["setuptools>=75.0", "setuptools_scm>=8.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "package-name"
dynamic = ["version"]
description = ""
readme = "README.md"
authors = [
    { name = "Niels Neerhoff", email = "nielsneerhoff@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[tool.setuptools_scm]
root = "../../"
version_file = "src/package_name/_version.py"
tag_regex = "^package-name/(?:[\\w-]+-)?(?P<version>[vV]?\\d+(?:\\.\\d+){0,2}[^\\+]*)(?:\\+.*)?$"
git_describe_command = "git describe --dirty --tags --long --match package-name/*"

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]